apiVersion: v1
kind: Service
metadata:
  name: bitcoin
  namespace: bitcoind
spec:
  selector:
    app: bitcoin
  ports:
    - protocol: TCP
      name: http
      port: 8332
      targetPort: 8332
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitcoin
  namespace: bitcoind
spec:
  serviceName: bitcoin
  replicas: 1 # Scale as match as you want
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: bitcoin
  template:
    metadata:
      labels:
        app: bitcoin
    spec:
      restartPolicy: Always
      containers:
        - name: bitcoin
          image: 9muta/bitcoind:22.0
          volumeMounts:
            - name: bitcoin
              mountPath: /root/.bitcoin
      imagePullSecrets:
        - name: regcred
  volumeClaimTemplates:
    - metadata:
        name: bitcoin
      spec:
        storageClassName: bitcoin-disk
        accessModes:
          - ReadWriteMany
        volumeMode: Filesystem
        resources:
          requests:
            storage: 500Gi