apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv0001
  namespace: bitcoind
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: bitcoin-disk
  #  mountOptions:
  #  - hard
  #  - nfsvers=4.1
  nfs:
    path: /pv
    server: 192.168.1.30